lr: 0.001
model_kwargs:
  c_feat_dynamic_cat:
  - 2
  - 2
  - 2
  - 31
  - 31
  - 5
  - 5
  c_feat_static_cat:
  - 3
  c_past_feat_dynamic_cat: []
  context_length: 28
  d_feat_dynamic_real:
  - 1
  - 1
  - 1
  - 32
  d_feat_static_real:
  - 1
  d_hidden: 64
  d_past_feat_dynamic_real: []
  d_var: 32
  distr_output: !!python/object/apply:copyreg.__newobj_ex__
    args:
    - !!python/name:gluonts.torch.distributions.quantile_output.QuantileOutput ''
    - !!python/tuple []
    - &id001 !!python/object/apply:collections.OrderedDict
      - - - quantiles
          - - 0.005
            - 0.025
            - 0.165
            - 0.25
            - 0.5
            - 0.75
            - 0.835
            - 0.975
            - 0.995
    state:
      __init_args__: *id001
      _quantiles:
      - 0.005
      - 0.025
      - 0.165
      - 0.25
      - 0.5
      - 0.75
      - 0.835
      - 0.975
      - 0.995
      args_dim:
        outputs: 9
      num_quantiles: 9
  dropout_rate: 0.1
  num_heads: 4
  prediction_length: 28
patience: 10
weight_decay: 1.0e-08
